name       : workrave
version    : 1.10.50
release    : 11
source     :
    - https://github.com/rcaelers/workrave/releases/download/v1_10_50/workrave-v1.10.50.tar.gz : d667444b933ef08d6f1471277acc650267868c2006c420a34feb1cb5cd64853b
homepage   : https://workrave.org/
license    : GPL-3.0-or-later
component  : desktop
summary    : Assists in the recovery and prevention of Repetitive Strain Injury (RSI)
description: |
    Workrave is a free program that assists in the recovery and prevention of Repetitive Strain Injury (RSI). It monitors your keyboard and mouse usage and using this information, it frequently alerts you to take microbreaks, rest breaks and restricts you to your daily computer usage.
builddeps  :
    - pkgconfig(ayatana-indicator3-0.4)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(dbusmenu-gtk3-0.4)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libpulse)
    - pkgconfig(sm)
    - pkgconfig(xscrnsaver)
    - autoconf-archive
    - libboost-devel
    - python-jinja
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install

    # Remove cinnamon stuff
    rm -rf $installdir/usr/share/cinnamon
