name       : workrave
version    : 1.10.20
release    : 2
source     :
    - https://github.com/rcaelers/workrave/archive/v1_10_20.tar.gz : a89c6e82d5bbbaae5e171100b87c4efd8316ab8a18d82b83714035e1116983ec
license    : GPL-3.0
component  : desktop
summary    : Workrave is a program that assists in the recovery and prevention of Repetitive Strain Injury (RSI)
description: |
    The program frequently alerts you to take micro-pauses, rest breaks and restricts you to your daily limit.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(dbusmenu-gtk3-0.4)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gdk-2.0)
    - pkgconfig(gio-2.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(ice)
    - pkgconfig(indicator3-0.4)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libpulse)
    - pkgconfig(sm)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - autoconf-archive
    - python-cheetah
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
    # remove cinnamon stuff
    rm -rf %installroot%/usr/share/cinnamon
