name       : workrave
version    : 1.10.44
release    : 7
source     :
    - https://github.com/rcaelers/workrave/archive/v1_10_44.tar.gz : 359a952b381d022afa036f23f67dab9aa1873e3aa8d1d4174108bcb8ea1768b1
license    : GPL-3.0-or-later
component  : desktop
summary    : Assists in the recovery and prevention of Repetitive Strain Injury (RSI)
description: |
    Workrave frequently alerts you to take micro-pauses, rest breaks and restricts you to your daily limit.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(dbusmenu-gtk3-0.4)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gdk-2.0)
    - pkgconfig(gio-2.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(ice)
    - pkgconfig(indicator3-0.4)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libpulse)
    - pkgconfig(sm)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - autoconf-archive
    - libboost-devel
    - python-jinja
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install

    # Remove cinnamon stuff
    rm -rf $installdir/usr/share/cinnamon
